// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkiEXn3Sn-w5cup_yGywJwLNzty8JWLU',
    appId: '1:216960031372:web:6f675b92c05cdff4cf39a9',
    messagingSenderId: '216960031372',
    projectId: 'csetfinal',
    authDomain: 'csetfinal.firebaseapp.com',
    storageBucket: 'csetfinal.firebasestorage.app',
    measurementId: 'G-4F7T01TQYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzV_MuzSx750ZpveWvVAFz3wrM_MV6P8',
    appId: '1:216960031372:android:fc4e39b2be8a78c4cf39a9',
    messagingSenderId: '216960031372',
    projectId: 'csetfinal',
    storageBucket: 'csetfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwvv1VChBxGwH7mff5TxMOEvPSFAPq0Y',
    appId: '1:216960031372:ios:b5c1cc8f80f89a94cf39a9',
    messagingSenderId: '216960031372',
    projectId: 'csetfinal',
    storageBucket: 'csetfinal.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwvv1VChBxGwH7mff5TxMOEvPSFAPq0Y',
    appId: '1:216960031372:ios:b5c1cc8f80f89a94cf39a9',
    messagingSenderId: '216960031372',
    projectId: 'csetfinal',
    storageBucket: 'csetfinal.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxkiEXn3Sn-w5cup_yGywJwLNzty8JWLU',
    appId: '1:216960031372:web:08c29f795b5599cccf39a9',
    messagingSenderId: '216960031372',
    projectId: 'csetfinal',
    authDomain: 'csetfinal.firebaseapp.com',
    storageBucket: 'csetfinal.firebasestorage.app',
    measurementId: 'G-C8F5X8E2S3',
  );
}
